name: Promote

on:
  # Approximate "every 2 weeks" by doing 1st and 15th of the month.
  schedule:
    - cron: "0 07 01 * *"
    - cron: "0 07 15 * *"

  workflow_dispatch:
    inputs:
      from:
        description: Tag to promote from
        required: true
        default: dev
      to:
        description: Tag to promote to
        required: true
        default: stable

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - uses: restyled-io/sdk@main
        with:
          command: |
            from=${{ github.event.from }}
            to=${{ github.event.to }}
            promote --yes "${from:-dev}" "${to:-stable}"
