name: Release to stable channel

on:
  # tags:
  #   - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to promote
        required: true
        default: dev

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: setup
        run: |
          docker pull restyled/sdk:main

          if [ -n "${{ github.event.inputs.tag }}" ]; then
            tag=${{ github.event.inputs.tag }}
          else
            tag=$(basename "${{ github.ref }}")
          fi

          echo "::set-output name=tag::$tag"

      - name: Promote to stable
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          docker run --rm \
            --env AWS_ACCESS_KEY_ID \
            --env AWS_SECRET_ACCESS_KEY \
            --env AWS_DEFAULT_REGION \
            --volume /tmp:/tmp \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            restyled/sdk:main promote --yes "${{ steps.setup.outputs.tag }}" stable
